#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys, os
from time import sleep
import aa_thumbnail, sys

files = sys.argv[1:]
files.sort()

# folder = sys.argv[1]
thumbpath = "thumbs" # os.path.join(".", "thumbs")
try:
    os.mkdir(thumbpath)
except OSError:
    pass

"""
eventually:
* group files of same basename
* include other metadata to do filtering / dynamic ordering.
* ability to edit metadata and write back (how?) to files

"""

print """<html>
<head>
<script src="lib/jquery-1.4.4.min.js"></script>
<script src="lib/json2.js"></script>
<script src="jquery.microdata.js"></script>
<script src="jquery.microdata.json.js"></script>
</head>
<body>
"""

for f in files:
    (base, ext) = os.path.splitext(f)
    ext = ext[1:].lower()
    if ext in ("jpg", "jpeg", "png"):
        preview = os.path.join(thumbpath, base+"_preview.jpg")
        thumb = os.path.join(thumbpath, base+"_thumbnail.jpg")
        print(aa_thumbnail.do(\
            originalpath=f,\
            resize="1024x768",\
            previewpath=preview,\
            thumbnailpath=thumb)
        )
    sleep(0.01)

print """</body>
</html>
"""

